version: '3'

services:
  pyroot:
    build:
      context: .
      dockerfile: ROOT.Dockerfile
      args:
        LATTES_REPO_ACCESS_TOKEN: $LATTES_REPO_ACCESS_TOKEN
    volumes:
       - ../:/mnt
    entrypoint: bash -c "cd /mnt && export PYTHONPATH='.' && /bin/bash"
    stdin_open: true
    container_name: "pyroot_${USER}"
    tty: true
    env_file:
      - ../.env

  postgres:
    image: postgres
    env_file:
      - ../.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ../:/mnt
    entrypoint: bash -c "mlflow server -h 0.0.0.0 -p 5000 && /bin/bash"
    stdin_open: true
    container_name: "mlflow_${USER}"
    tty: true
    env_file:
      - ../.env

volumes:
  database-data:
